# -*- coding: utf-8 -*-
"""11724 연결요소의 개수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12y_FmgsyhJihEvUkBnOBUOLifVTEMmqo
"""

import sys
sys.setrecursionlimit(10000)
#n : 정점, m : 간선
n, m = map(int, input().split())

#그래프 세팅
graph = [[0]*(n+1) for _ in range(n+1)]
visited = [0 for _ in range(n+1)]
cnt = 0

def dfs(i):
    visited[i] = 1
    for k in range(1, n+1):
        if graph[i][k] == 1 and visited[k] == 0:
            dfs(k)

for i in range(m):
    a,b = map(int, input().split())
    graph[a][b] = 1
    graph[b][a] = 1

for i in range(1,n+1):
    if visited[i] == 0:
        dfs(i)
        cnt += 1
print(cnt)